[theme]
base="light"
primaryColor="#FFC0CB"       
backgroundColor="#ffffff"          
secondaryBackgroundColor="#FFB6C1"  
textColor="#1f2335"                
font="monospace"                   





